"""initial schema

Revision ID: b3ea7b500e54
Revises: 
Create Date: 2026-06-12 00:11:08.234228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b3ea7b500e54'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('severity', sa.String(length=8), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('channels', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.Column('delivery_detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_kind'), 'alerts', ['kind'], unique=False)
    op.create_index(op.f('ix_alerts_ts'), 'alerts', ['ts'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_ts'), 'audit_log', ['ts'], unique=False)
    op.create_table('backtest_runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('git_rev', sa.String(length=64), nullable=False),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('equity_curve', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('artifacts', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_runs_created_at'), 'backtest_runs', ['created_at'], unique=False)
    op.create_table('commands',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('acked_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commands_created_at'), 'commands', ['created_at'], unique=False)
    op.create_index(op.f('ix_commands_kind'), 'commands', ['kind'], unique=False)
    op.create_index(op.f('ix_commands_status'), 'commands', ['status'], unique=False)
    op.create_table('config_versions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('old_value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('new_value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_config_versions_key'), 'config_versions', ['key'], unique=False)
    op.create_index(op.f('ix_config_versions_ts'), 'config_versions', ['ts'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('equity', sa.Float(), nullable=False),
    sa.Column('tier_name', sa.String(length=16), nullable=False),
    sa.Column('regime_label', sa.String(length=32), nullable=False),
    sa.Column('regime_probs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('regime_source', sa.String(length=16), nullable=False),
    sa.Column('risk_frac_eff', sa.Float(), nullable=False),
    sa.Column('vol_scaler', sa.Float(), nullable=False),
    sa.Column('kelly', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('halted', sa.Boolean(), nullable=False),
    sa.Column('kill_reason', sa.String(length=64), nullable=True),
    sa.Column('signals', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('targets', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('orders', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('audit', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_mode'), 'decisions', ['mode'], unique=False)
    op.create_index('ix_decisions_mode_ts', 'decisions', ['mode', 'ts'], unique=False)
    op.create_index(op.f('ix_decisions_ts'), 'decisions', ['ts'], unique=False)
    op.create_table('engine_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=True),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('host', sa.String(length=128), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('market_open', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equity_curve',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('equity', sa.Float(), nullable=False),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.Column('mtm', sa.Float(), nullable=False),
    sa.Column('gross_exposure', sa.Float(), nullable=False),
    sa.Column('net_exposure', sa.Float(), nullable=False),
    sa.Column('realized_pnl', sa.Float(), nullable=False),
    sa.Column('unrealized_pnl', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equity_curve_mode'), 'equity_curve', ['mode'], unique=False)
    op.create_index(op.f('ix_equity_curve_ts'), 'equity_curve', ['ts'], unique=False)
    op.create_index('ix_equity_mode_ts', 'equity_curve', ['mode', 'ts'], unique=False)
    op.create_table('market_bars',
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('tf_minutes', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('symbol', 'tf_minutes', 'ts')
    )
    op.create_table('pnl_attribution',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('strategy', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('regime', sa.String(length=32), nullable=False),
    sa.Column('gross_pnl', sa.Float(), nullable=False),
    sa.Column('fees', sa.Float(), nullable=False),
    sa.Column('net_pnl', sa.Float(), nullable=False),
    sa.Column('n_trades', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'mode', 'strategy', 'symbol', 'regime', name='uq_pnl_attr_bucket')
    )
    op.create_index(op.f('ix_pnl_attribution_date'), 'pnl_attribution', ['date'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('strategy', sa.String(length=64), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('avg_price', sa.Float(), nullable=False),
    sa.Column('stop_distance', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('realized_pnl', sa.Float(), nullable=False),
    sa.Column('fees_paid', sa.Float(), nullable=False),
    sa.Column('entry_decision_id', sa.BigInteger(), nullable=True),
    sa.Column('exit_decision_id', sa.BigInteger(), nullable=True),
    sa.Column('entry_rationale', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('exit_rationale', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_mode'), 'positions', ['mode'], unique=False)
    op.create_index('ix_positions_mode_status', 'positions', ['mode', 'status'], unique=False)
    op.create_index(op.f('ix_positions_status'), 'positions', ['status'], unique=False)
    op.create_index(op.f('ix_positions_symbol'), 'positions', ['symbol'], unique=False)
    op.create_table('regime_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('label', sa.String(length=32), nullable=False),
    sa.Column('probs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('risk_scaler', sa.Float(), nullable=False),
    sa.Column('strategy_weights', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regime_history_ts'), 'regime_history', ['ts'], unique=False)
    op.create_table('risk_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('rule', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=True),
    sa.Column('severity', sa.String(length=8), nullable=False),
    sa.Column('cause', sa.Text(), nullable=False),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('decision_id', sa.BigInteger(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_events_kind'), 'risk_events', ['kind'], unique=False)
    op.create_index(op.f('ix_risk_events_mode'), 'risk_events', ['mode'], unique=False)
    op.create_index(op.f('ix_risk_events_ts'), 'risk_events', ['ts'], unique=False)
    op.create_table('runtime_config',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('strategy_stats',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('strategy', sa.String(length=64), nullable=False),
    sa.Column('mu', sa.Float(), nullable=False),
    sa.Column('var', sa.Float(), nullable=False),
    sa.Column('n_eff', sa.Float(), nullable=False),
    sa.Column('kelly_f', sa.Float(), nullable=False),
    sa.Column('sharpe_ann', sa.Float(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('incubating', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_stats_strategy'), 'strategy_stats', ['strategy'], unique=False)
    op.create_index(op.f('ix_strategy_stats_ts'), 'strategy_stats', ['ts'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('totp_secret', sa.String(length=64), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('webhook_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_webhook_source_ext')
    )
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('client_order_id', sa.String(length=64), nullable=False),
    sa.Column('decision_id', sa.BigInteger(), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('strategy', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('filled_qty', sa.Integer(), nullable=False),
    sa.Column('style', sa.String(length=24), nullable=False),
    sa.Column('urgency', sa.String(length=16), nullable=False),
    sa.Column('limit_price', sa.Float(), nullable=True),
    sa.Column('ref_price', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('broker_order_id', sa.String(length=64), nullable=False),
    sa.Column('reject_reason', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status_history', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_order_id')
    )
    op.create_index(op.f('ix_orders_broker_order_id'), 'orders', ['broker_order_id'], unique=False)
    op.create_index(op.f('ix_orders_mode'), 'orders', ['mode'], unique=False)
    op.create_index('ix_orders_mode_ts', 'orders', ['mode', 'ts'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_symbol'), 'orders', ['symbol'], unique=False)
    op.create_index(op.f('ix_orders_ts'), 'orders', ['ts'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('reauth_at', sa.DateTime(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=256), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('fills',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('client_order_id', sa.String(length=64), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('strategy', sa.String(length=64), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('fees_total', sa.Float(), nullable=False),
    sa.Column('fees', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('slippage', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fills_client_order_id'), 'fills', ['client_order_id'], unique=False)
    op.create_index(op.f('ix_fills_mode'), 'fills', ['mode'], unique=False)
    op.create_index(op.f('ix_fills_symbol'), 'fills', ['symbol'], unique=False)
    op.create_index(op.f('ix_fills_ts'), 'fills', ['ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fills_ts'), table_name='fills')
    op.drop_index(op.f('ix_fills_symbol'), table_name='fills')
    op.drop_index(op.f('ix_fills_mode'), table_name='fills')
    op.drop_index(op.f('ix_fills_client_order_id'), table_name='fills')
    op.drop_table('fills')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_orders_ts'), table_name='orders')
    op.drop_index(op.f('ix_orders_symbol'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index('ix_orders_mode_ts', table_name='orders')
    op.drop_index(op.f('ix_orders_mode'), table_name='orders')
    op.drop_index(op.f('ix_orders_broker_order_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('webhook_events')
    op.drop_table('users')
    op.drop_index(op.f('ix_strategy_stats_ts'), table_name='strategy_stats')
    op.drop_index(op.f('ix_strategy_stats_strategy'), table_name='strategy_stats')
    op.drop_table('strategy_stats')
    op.drop_table('runtime_config')
    op.drop_index(op.f('ix_risk_events_ts'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_mode'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_kind'), table_name='risk_events')
    op.drop_table('risk_events')
    op.drop_index(op.f('ix_regime_history_ts'), table_name='regime_history')
    op.drop_table('regime_history')
    op.drop_index(op.f('ix_positions_symbol'), table_name='positions')
    op.drop_index(op.f('ix_positions_status'), table_name='positions')
    op.drop_index('ix_positions_mode_status', table_name='positions')
    op.drop_index(op.f('ix_positions_mode'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_pnl_attribution_date'), table_name='pnl_attribution')
    op.drop_table('pnl_attribution')
    op.drop_table('market_bars')
    op.drop_index('ix_equity_mode_ts', table_name='equity_curve')
    op.drop_index(op.f('ix_equity_curve_ts'), table_name='equity_curve')
    op.drop_index(op.f('ix_equity_curve_mode'), table_name='equity_curve')
    op.drop_table('equity_curve')
    op.drop_table('engine_status')
    op.drop_index(op.f('ix_decisions_ts'), table_name='decisions')
    op.drop_index('ix_decisions_mode_ts', table_name='decisions')
    op.drop_index(op.f('ix_decisions_mode'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_config_versions_ts'), table_name='config_versions')
    op.drop_index(op.f('ix_config_versions_key'), table_name='config_versions')
    op.drop_table('config_versions')
    op.drop_index(op.f('ix_commands_status'), table_name='commands')
    op.drop_index(op.f('ix_commands_kind'), table_name='commands')
    op.drop_index(op.f('ix_commands_created_at'), table_name='commands')
    op.drop_table('commands')
    op.drop_index(op.f('ix_backtest_runs_created_at'), table_name='backtest_runs')
    op.drop_table('backtest_runs')
    op.drop_index(op.f('ix_audit_log_ts'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_alerts_ts'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_kind'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
